coverage_service: cobertura_xml
xcodeproj: SwiftSky.xcodeproj
workspace: SwiftSky.xcworkspace
scheme: SwiftSky iOS
configuration: Debug
source_directory: Source
output_directory: coverage/
ignore:
  - Tests/*
